language: python
dist: bionic

matrix:
  include:
    - python: "2.7"
    - python: "3.4"
      dist: xenial
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      sudo: true
      script:
        - ./dmenv run -- pytest --cov=tankersdk_identity
        - codecov
    - python: "3.8"

install:
  - curl -L https://github.com/TankerHQ/dmenv/releases/download/v0.20.0/dmenv-linux -o dmenv
  - chmod u+x dmenv
  - ./dmenv install


script:
  - ./dmenv run pytest
