language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run python setup.py develop


script:
  - pipenv check
  - pipenv run pytest
